### PR TITLE
Add Rspec

### LINKED ISSUE #6: Add rspec

### PR DESCRIPTION
**Pull request by pdany1116**
#### Description

Add Rspec testing library with a sample test.

### CODE REVIEW

**Review by cazacutudor — COMMENTED** [review]
Looks good,

Let's merge it once we update the README.md, with specs running steps.

**Comment by pdany1116** [comment]
I messed up with a rebase when adding Add Docker commit. The history looks ugly but nothing broke.

**Comment by cazacutudor** [comment]
Let's rebase on master, and get rid of the additional commits.

**Comment by pdany1116** [comment]
After or before I merge this?

**Pull request merged**
